### ISSUE TITLE
Method 'start' should not return a value

### ISSUE THREAD

**Issue by heaversm** [2bbb/ofxMacScreenRecorder#1]
Getting an error in `ofxMacScreenRecorder.mm`: `method start should not return a value`

<img width="1086" alt="screen shot 2017-10-23 at 8 31 24 am" src="https://user-images.githubusercontent.com/520541/31897944-afc9b388-b7cc-11e7-8c9b-3b58b70dff6f.png">

By commenting out the return values in the start function, then capturing the screen, the rendered test.mov file cannot be played (at least on a mac). Tried in VLC and Quicktime.

**Comment by 2bbb** [comment]
fixed.

thanks!
